id: P009472
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:40:23.005970
source_metadata:
  id: bdr:W22319
  title: གསེར་འོད་གཡང་སྐྱབས
  author: ''
  volumes:
    8e8171f4c0e44b8fa09528261e7d50f1:
      image_group_id: I1PD36243
      title: ''
      volume_number: 1
      total_pages: 52
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
