id: I62B76A66
legacy_id: P009472
ocr_import_info:
  bdrc_scan_id: W22319
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T14:59:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T21:23:06.105318+00:00'
last_modified: 2022-09-02 05:23:10.732297
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22319
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22319
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསེར་འོད་གཡང་སྐྱབས།
statistics:
  ocr_word_mean_confidence_index: 0.5165810970185981
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I1PD36243:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD36243
      total_pages: 52
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD36243.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.5165810970185981
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
